name: CI

on:
  push:
    branches: [main, sprint2/gate-unification]
  pull_request:
    branches: [main, sprint2/gate-unification]

jobs:
  python-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install
        run: |
          python -m pip install --upgrade pip
          pip install -e ".[dev]"
      - name: Pytest
        run: pytest -q

  coq-skeleton:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Coq
        run: |
          sudo apt-get update
          sudo apt-get install -y coq
      - name: Compile Coq Skeletons
        run: |
          coqc coq/Gates/GateSukun.v
          coqc coq/Gates/GateShadda.v
          coqc coq/Gates/GateTanwin.v
