# -*- coding: utf-8 -*-
"""
Stage 15 DEPENDENCY_SYNTAX_BUILDER — explicit dependency graph from L10B signals.
Pass A: nominal/verbal. Pass B: PP, idafa, SIFA. Pass C: coordination, apposition, ambiguity_log, candidate_markers.
Non-destructive; reads L4, L5, L8, L8B, L10B. Root only in root_resolution.
"""

from .builder import build_dependency_syntax
from .relation_inventory import (
    AR_ATF,
    AR_ATF_CONJ,
    AR_BADAL,
    AR_FAIL,
    AR_JAR_MAJRUR,
    AR_KHABAR,
    AR_MAF3UL_BIH,
    AR_MUBTADA,
    AR_MUDAF,
    AR_NA3T,
    AR_NAIB_FAIL,
    AR_ISM_INNA,
    AR_PP_ATTACH,
    PASS_A_RELATIONS,
    PASS_B_RELATIONS,
    PASS_C_RELATIONS,
    PASS_C_MARKERS_ONLY,
    REL_APPOS,
    REL_COORD,
    REL_COORD_CONJ,
    REL_HAL_CAND,
    REL_IDAFA,
    REL_INNA_NAME,
    REL_JAR_MAJRUR,
    REL_NAIB_SUBJ,
    REL_OBJ,
    REL_PP_ATTACH,
    REL_PRED,
    REL_SIFA,
    REL_SUBJ,
    REL_TAMYIZ_CAND,
    get_relation_spec,
)

__all__ = [
    "build_dependency_syntax",
    "REL_SUBJ",
    "REL_OBJ",
    "REL_PRED",
    "REL_NAIB_SUBJ",
    "REL_JAR_MAJRUR",
    "REL_PP_ATTACH",
    "REL_IDAFA",
    "REL_SIFA",
    "REL_INNA_NAME",
    "REL_COORD",
    "REL_COORD_CONJ",
    "REL_APPOS",
    "REL_TAMYIZ_CAND",
    "REL_HAL_CAND",
    "AR_FAIL",
    "AR_MUBTADA",
    "AR_MAF3UL_BIH",
    "AR_KHABAR",
    "AR_NAIB_FAIL",
    "AR_JAR_MAJRUR",
    "AR_PP_ATTACH",
    "AR_MUDAF",
    "AR_NA3T",
    "AR_ISM_INNA",
    "AR_ATF",
    "AR_ATF_CONJ",
    "AR_BADAL",
    "PASS_A_RELATIONS",
    "PASS_B_RELATIONS",
    "PASS_C_RELATIONS",
    "PASS_C_MARKERS_ONLY",
    "get_relation_spec",
]
