"""FastAPI web application for Arabic grammar activities.

This module provides a web interface to display grammar activities
generated by various engine classes.
"""

import logging
from datetime import datetime
from typing import List, Optional

from fastapi import FastAPI
from fastapi.responses import HTMLResponse
from pydantic import BaseModel, Field

# Configure logging
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(name)s - %(levelname)s - %(message)s'
)
logger = logging.getLogger(__name__)

# Global cache for engines list
ENGINES: Optional[List] = None

# Pydantic response models
class Activity(BaseModel):
    """Model for a single activity."""
    name: str = Field(..., description="Name of the activity (sheet name)")
    engine_class: str = Field(..., description="Engine class name")

class ActivitiesResponse(BaseModel):
    """Response model for /api/activities endpoint."""
    date: str = Field(..., description="Current date in ISO format")
    total_activities: int = Field(..., description="Total number of activities available")
    activities: List[Activity] = Field(..., description="List of available activities")


app = FastAPI(
    title="Arabic Grammar Activities API",
    description="API for exploring Arabic grammar activities generated by various engines",
    version="1.0.0"
)


@app.on_event("startup")
async def startup_event():
    """Load available engine classes once on application startup."""
    global ENGINES
    
    logger.info("Starting up: loading engine classes...")
    
    try:
        # Import collect_engines from Main_engine module
        from Main_engine import collect_engines
        
        # Call collect_engines to get list of engine classes
        engines = collect_engines()
        
        # Validate that we got a list
        if not isinstance(engines, list):
            logger.warning(
                f"collect_engines() returned unexpected type: {type(engines).__name__}. "
                f"Expected list. Defaulting to empty list."
            )
            ENGINES = []
        else:
            ENGINES = engines
            logger.info(f"Successfully loaded {len(ENGINES)} engine classes")
            
            # Log engine names for debugging
            for engine in ENGINES:
                sheet_name = getattr(engine, 'SHEET_NAME', 'Unknown')
                logger.debug("  - %s: %s", engine.__name__, sheet_name)
                
    except ImportError as e:
        logger.error(
            f"Failed to import Main_engine.collect_engines: {e}. "
            f"Make sure Main_engine.py exists and is importable."
        )
        ENGINES = []
    except Exception as e:
        logger.error(f"Error during engine collection: {e}")
        ENGINES = []
    
    if not ENGINES:
        logger.warning(
            "No engines loaded! The application will start but /api/activities will be empty. "
            "Verify that Main_engine.py exists and provides collect_engines()."
        )


@app.get("/", response_class=HTMLResponse)
async def root():
    """Serve a simple HTML UI."""
    html_content = """
    <!DOCTYPE html>
    <html lang="ar" dir="rtl">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Arabic Grammar Activities</title>
        <style>
            body {
                font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
                max-width: 1200px;
                margin: 0 auto;
                padding: 20px;
                background-color: #f5f5f5;
            }
            h1 {
                color: #2c3e50;
                text-align: center;
            }
            .info {
                background-color: #e8f4f8;
                border-left: 4px solid #3498db;
                padding: 15px;
                margin: 20px 0;
            }
            .activities-container {
                background-color: white;
                border-radius: 8px;
                padding: 20px;
                box-shadow: 0 2px 4px rgba(0,0,0,0.1);
                margin-top: 20px;
            }
            .activity-item {
                padding: 12px;
                border-bottom: 1px solid #ecf0f1;
                display: flex;
                justify-content: space-between;
                align-items: center;
            }
            .activity-item:last-child {
                border-bottom: none;
            }
            .activity-name {
                font-weight: bold;
                color: #2c3e50;
            }
            .activity-class {
                color: #7f8c8d;
                font-size: 0.9em;
            }
            .loading {
                text-align: center;
                padding: 20px;
                color: #7f8c8d;
            }
            .error {
                background-color: #fee;
                border-left: 4px solid #e74c3c;
                padding: 15px;
                margin: 20px 0;
                color: #c0392b;
            }
            button {
                background-color: #3498db;
                color: white;
                border: none;
                padding: 10px 20px;
                border-radius: 4px;
                cursor: pointer;
                font-size: 16px;
            }
            button:hover {
                background-color: #2980b9;
            }
        </style>
    </head>
    <body>
        <h1>🎓 نظام أنشطة القواعد العربية</h1>
        <h2 style="text-align: center; color: #7f8c8d;">Arabic Grammar Activities System</h2>
        
        <div class="info">
            <p><strong>Welcome!</strong> This application displays available Arabic grammar activities.</p>
            <p>API Endpoint: <a href="/api/activities">/api/activities</a></p>
            <p>Documentation: <a href="/docs">/docs</a></p>
        </div>
        
        <div style="text-align: center; margin: 20px 0;">
            <button onclick="loadActivities()">تحميل الأنشطة / Load Activities</button>
        </div>
        
        <div id="activities-display" class="activities-container">
            <div class="loading">Click the button above to load activities</div>
        </div>
        
        <script>
            async function loadActivities() {
                const display = document.getElementById('activities-display');
                display.innerHTML = '<div class="loading">Loading activities...</div>';
                
                try {
                    const response = await fetch('/api/activities');
                    if (!response.ok) {
                        throw new Error(`HTTP error! status: ${response.status}`);
                    }
                    const data = await response.json();
                    
                    let html = `
                        <h3>Total Activities: ${data.total_activities}</h3>
                        <p>Date: ${data.date}</p>
                    `;
                    
                    if (data.activities.length === 0) {
                        html += '<div class="error">No activities available. Check server logs.</div>';
                    } else {
                        data.activities.forEach(activity => {
                            html += `
                                <div class="activity-item">
                                    <span class="activity-name">${activity.name}</span>
                                    <span class="activity-class">${activity.engine_class}</span>
                                </div>
                            `;
                        });
                    }
                    
                    display.innerHTML = html;
                } catch (error) {
                    display.innerHTML = `<div class="error">Error loading activities: ${error.message}</div>`;
                    console.error('Error:', error);
                }
            }
        </script>
    </body>
    </html>
    """
    return html_content


@app.get("/api/activities", response_model=ActivitiesResponse)
async def get_activities():
    """Get list of available activities.
    
    Returns:
        ActivitiesResponse: Object containing date, total count, and list of activities
    """
    if ENGINES is None:
        logger.warning("ENGINES cache is None - startup may not have completed")
        activities = []
    else:
        activities = []
        for engine_cls in ENGINES:
            try:
                sheet_name = getattr(engine_cls, 'SHEET_NAME', engine_cls.__name__)
                activities.append(
                    Activity(
                        name=sheet_name,
                        engine_class=engine_cls.__name__
                    )
                )
            except Exception as e:
                logger.error(f"Error processing engine {engine_cls}: {e}")
                continue
    
    return ActivitiesResponse(
        date=datetime.now().isoformat(),
        total_activities=len(activities),
        activities=activities
    )
